/**
 * -----------------------------------------------------------------------------
 * CreateSAMLAssertion.java
 * -----------------------------------------------------------------------------
 *
 * Demonstrates how a simple SAML Assertion can be represented as XML.
 *
 * A SAML Assertion is an XML document generated by an Identity Provider (IdP)
 * after successfully authenticating a user.
 *
 * The assertion is later sent to a Service Provider (SP), which verifies the
 * digital signature before granting access to the requested application.
 *
 * NOTE:
 * This example generates a simplified SAML Assertion for educational purposes.
 * A production SAML Assertion contains many additional elements including:
 *
 *      • XML Namespace declarations
 *      • Digital Signature
 *      • Conditions
 *      • Timestamps
 *      • Audience Restrictions
 *      • Session Information
 *
 * Time Complexity:
 *      O(1)
 *
 * -----------------------------------------------------------------------------
 */
public class CreateSAMLAssertion {

    /**
     * Program entry point.
     */
    public static void main(String[] args) {

        /*
         * Create a simplified SAML Assertion.
         */
        String samlAssertion = """

<saml:Assertion>

    <saml:Issuer>

        https://login.clockwiseknowledge.com

    </saml:Issuer>

    <saml:Subject>

        <saml:NameID>

            sanjay.ghosh@clockwiseknowledge.com

        </saml:NameID>

    </saml:Subject>

    <saml:AuthnStatement>

        Authentication Method = Multi-Factor Authentication

    </saml:AuthnStatement>

    <saml:AttributeStatement>

        <Email>

            sanjay.ghosh@company.com

        </Email>

        <Department>

            Engineering

        </Department>

        <Role>

            Administrator

        </Role>

    </saml:AttributeStatement>

</saml:Assertion>

""";

        System.out.println("----------------------------------------");
        System.out.println("Generated SAML Assertion");
        System.out.println("----------------------------------------");

        System.out.println(samlAssertion);
    }
}
