import java.io.ByteArrayInputStream;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 * -----------------------------------------------------------------------------
 * ParseSAMLAssertion.java
 * -----------------------------------------------------------------------------
 *
 * Demonstrates how to parse a simplified SAML Assertion using Java's
 * DOM (Document Object Model) Parser.
 *
 * A SAML Assertion is an XML document generated by an Identity Provider (IdP)
 * after successfully authenticating a user.
 *
 * In this example, we extract the following information:
 *
 *      • Issuer
 *      • User NameID
 *      • Authentication Method
 *      • Email
 *      • Department
 *      • Role
 *
 * NOTE:
 * Production SAML Assertions contain many additional XML elements,
 * namespaces, digital signatures, timestamps, and conditions.
 * This example uses a simplified XML document for learning purposes.
 *
 * Time Complexity:
 *      O(n)
 *      where n is the number of XML nodes.
 *
 * -----------------------------------------------------------------------------
 */
public class ParseSAMLAssertion {

    /**
     * Program entry point.
     */
    public static void main(String[] args) throws Exception {

        /*
         * Sample SAML Assertion.
         */
        String samlAssertion = """

<saml:Assertion>

    <saml:Issuer>

        https://login.clockwiseknowledge.com

    </saml:Issuer>

    <saml:Subject>

        <saml:NameID>

            sanjay.ghosh@clockwiseknowledge.com

        </saml:NameID>

    </saml:Subject>

    <saml:AuthnStatement>

        Multi-Factor Authentication

    </saml:AuthnStatement>

    <saml:AttributeStatement>

        <Email>

            sanjay.ghosh@clockwiseknowledge.com

        </Email>

        <Department>

            Engineering

        </Department>

        <Role>

            Administrator

        </Role>

    </saml:AttributeStatement>

</saml:Assertion>

""";

        /*
         * The XML uses the "saml:" prefix for readability.
         * Since this example does not define namespaces,
         * remove the prefix before parsing.
         */
        samlAssertion = samlAssertion.replace("saml:", "");

        /*
         * Create a DOM Parser.
         */
        DocumentBuilderFactory factory =
                DocumentBuilderFactory.newInstance();

        DocumentBuilder builder =
                factory.newDocumentBuilder();

        /*
         * Parse the XML into a DOM Document.
         */
        Document document = builder.parse(
                new ByteArrayInputStream(samlAssertion.getBytes()));

        document.getDocumentElement().normalize();

        /*
         * Extract XML values.
         */
        String issuer =
                getValue(document, "Issuer");

        String nameID =
                getValue(document, "NameID");

        String authMethod =
                getValue(document, "AuthnStatement");

        String email =
                getValue(document, "Email");

        String department =
                getValue(document, "Department");

        String role =
                getValue(document, "Role");

        /*
         * Display extracted information.
         */
        System.out.println("--------------------------------------------");
        System.out.println("Parsed SAML Assertion");
        System.out.println("--------------------------------------------");

        System.out.println("Issuer              : " + issuer);
        System.out.println("User                : " + nameID);
        System.out.println("Authentication      : " + authMethod);
        System.out.println("Email               : " + email);
        System.out.println("Department          : " + department);
        System.out.println("Role                : " + role);
    }

    /**
     * Returns the text value of the first XML element
     * with the specified tag name.
     *
     * @param document Parsed XML document.
     * @param tagName  XML tag.
     *
     * @return Element value.
     */
    private static String getValue(Document document,
                                   String tagName) {

        NodeList nodes =
                document.getElementsByTagName(tagName);

        if (nodes.getLength() == 0) {
            return "";
        }

        Element element = (Element) nodes.item(0);

        return element.getTextContent().trim();
    }
}
